version: "3.8"
services:
  db:
    image: "postgres:14"
    ports:
      - "23432:5432"
    volumes:
      - /home/ddalpra/docker/volume/pgdd1:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=admin2021
      - POSTGRES_DB=todoapp

